### PR TITLE
Remove geo-service task definition and log group

### PR DESCRIPTION
**Pull request by mannykary**
Remove geo-service Fargate task definition

### CODE REVIEW

**Review by joshmorel — APPROVED** [review]
lgtm

**Review by joshmorel — CHANGES_REQUESTED** [review]
@mannykary  - one thing I forgot we have a new key - `GOOGLE_MAPS_API_KEY` do we need to add something about it in the test.tf like the other env vars?

**Comment by mannykary** [comment]
@joshmorel Nope, the backend environment variables are being passed into this module as a list from the `main.tf` file in the main repo, and it looks like you added it to the list, so there's no need to explicitly define it here since it will just take that list and add it to the task definition JSON file.

**Comment by mannykary** [comment]
@joshmorel I'll hold off on merging this until we have your PR merged in. Otherwise, it will break deploys for staging and production.

**Pull request merged**
